USE [MVCTrainingDB]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 17-07-2020 3.02.33 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Employees]') AND type in (N'U'))
DROP TABLE [dbo].[Employees]
GO
USE [master]
GO
/****** Object:  Database [MVCTrainingDB]    Script Date: 17-07-2020 3.02.33 PM ******/
DROP DATABASE [MVCTrainingDB]
GO
/****** Object:  Database [MVCTrainingDB]    Script Date: 17-07-2020 3.02.33 PM ******/
CREATE DATABASE [MVCTrainingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MVCTrainingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MVCTrainingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MVCTrainingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MVCTrainingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MVCTrainingDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVCTrainingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MVCTrainingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MVCTrainingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MVCTrainingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MVCTrainingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MVCTrainingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MVCTrainingDB] SET  MULTI_USER 
GO
ALTER DATABASE [MVCTrainingDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MVCTrainingDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MVCTrainingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MVCTrainingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MVCTrainingDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MVCTrainingDB] SET QUERY_STORE = OFF
GO
USE [MVCTrainingDB]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 17-07-2020 3.02.33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmpName] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[Phone] [varchar](20) NULL,
	[Address] [varchar](100) NULL,
 CONSTRAINT [PK__Employee__3214EC074C3A3E11] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MVCTrainingDB] SET  READ_WRITE 
GO
